spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/final_db
    username: postgres
    password: bebra2281
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081